/// List of profane English words taken from [LDNOOBW on GitHub](
///https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words).
List<String> defaultWordsToFilterOutList = [
  '❤️',
  '💕',
  '😘',
  '💖',
  '💋',
  '💌',
  '💘',
  '💝',
  '💗',
  '💓',
  '💞',
  '💕',
  '💟',
  '❤️‍🔥',
  '❤️',
  '💏',
  '💛',
  '💚',
  '💙',
  '🥰',
  '😍',
  '🤤',
  '😽',
  '😻',
  '🙈',
  '👙',
  '♥️',
  '🤎',
  '🖤',
  '🤍',
  '❤️‍🩹',
  '❣️',
  '💋',
  '🫂',
  '😗',
  '😙',
  '❣️',
  'Love you',
  'love you',
  'i love u',
  'i love u',
  'i luv u',
  'luv u',
  'LOVE YOU',
  'love u',
  'you are my everything',
  'will you marry me',
  'marry me',
  'you are gorguous',
  'kiss me',
  'hug me',
  'ly',
  'lysm',
  'lyssm',
  'hey bby',
  'baby',
  'hey babe',
  'hey cute',
  'hey bby',
  'hey handsome',
  'You’re so beautiful',
  'You’re so handsome',
  'You are handsome',
  'You are beautiful',
  'hey beautiful',
  'hey sexy',
  'How are you still single',
  'I’m falling for you',
  'You are hot',
  'I think I like you',
  'date me',
  'date you',
  'i am nothing without you',
  'We should probably go on another date soon',
  'you are perfect for me',
  'I could text you all night',
  'love u machaa',
  'ummaah',
  'ummaahh',
  'ummmmmaaaahh',
  'kattipudi',
];
