// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIrmnu57QoOF7VTNYywfOp6PBpdWQT-hI',
    appId: '1:353643620104:web:54ff44c11d78b4b0e36ebd',
    messagingSenderId: '353643620104',
    projectId: 'sd-whatsapp-44a59',
    authDomain: 'sd-whatsapp-44a59.firebaseapp.com',
    storageBucket: 'sd-whatsapp-44a59.appspot.com',
    measurementId: 'G-JQSSHG1YWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapciaKtU1rtg45SlWbkiCEqLgldtecGM',
    appId: '1:353643620104:android:6542cfbba58695ede36ebd',
    messagingSenderId: '353643620104',
    projectId: 'sd-whatsapp-44a59',
    storageBucket: 'sd-whatsapp-44a59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARHKrPj_P9-Qg6O14nyHJ7QxFVtlKqF9I',
    appId: '1:353643620104:ios:2b01cfba1418dd6ce36ebd',
    messagingSenderId: '353643620104',
    projectId: 'sd-whatsapp-44a59',
    storageBucket: 'sd-whatsapp-44a59.appspot.com',
    iosClientId: '353643620104-cgk05dlrn1efo5k9g4fripbb6clu8s6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fairChat',
  );
}
